### ISSUE TITLE
Issue using Certes-CLI

### ISSUE THREAD

**Issue by pkiguy** [fszlin/certes#141]
Hello,

Using Certes-CLI, when trying to get an authorization, i get the following stacktrace:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Certes.Acme.OrderContext.Authorizations() in C:\projects\certes\src\Certes\Acme\OrderContext.cs:line 31
   at Certes.IOrderContextExtensions.Authorization(IOrderContext context, String value, IdentifierType type) in C:\projects\certes\src\Certes\Extensions\IOrderContextExtensions.cs:line 102
   at Certes.Cli.Commands.OrderAuthzCommand.Execute(ArgumentSyntax syntax) in C:\projects\certes\src\Certes.Cli\Commands\OrderAuthzCommand.cs:line 60
   at Certes.Cli.CliCore.Run(String[] args) in C:\projects\certes\src\Certes.Cli\CliCore.cs:line 35
```

And i don't know at all why it's failing. Any idea?

**Comment by fszlin** [comment]
Do you mind share the command, and order uri?
I suspect the order hasn't been created.

**Comment by pkiguy** [comment]
Actually, i'm using a private instance of Boulder, because i wanted to test it (it works with certbot, as a matter of fact). The order has been created, and the command looks like:
certes order authz https://acme-test.example.com/acme/order/6098744/3777441 test.example.com http

**Comment by fszlin** [comment]
Could you try the commands on LE staging? I think I will need to take a look at the order content.
And I am not sure how certbot initialize the order... :cold_sweat:

**Comment by pkiguy** [comment]
on LE staging it's working, strangely... but also the reply from the "order new" command is much more verbose: in LE staging case, i get the full JSON reply, where on my internal Boulder instance, i get only the "location" line. Could that be a glitch in JSON parsing following to the "order new" command? Is there a way to enable more verbosity there?

**Comment by fszlin** [comment]
Did you see any log from your internal Boulder may have more details?

**Comment by pkiguy** [comment]
hum. i re-downloaded and re-built Boulder, and the issue disappeared! Sorry for the inconvenience.
