### ISSUE TITLE
Issue building certificate chain

### ISSUE THREAD

**Issue by pkiguy** [fszlin/certes#142]
Hello again,

I'm still working on my private Boulder instance. Now everything seems to work, except for retrieving the certificate at the very end.
If i understand correctly the code, you always try to build a full certificate chain from Boulder issued certificates and from the CA certificates that are already included into Certes lib... This translates into the following error:
```
Certes.AcmeException: Can not find issuer 'DC=com,DC=example,CN=example-srv-CA' for certificate 'CN=test.example.com'.
   at Certes.Pkcs.CertificateStore.GetIssuers(Byte[] der) in C:\projects\certes\src\Certes\Pkcs\CertificationStore.cs:line 58
   at Certes.CertificateChainExtensions.ToPem(CertificateChain certificateChain, IKey certKey) in C:\projects\certes\src\Certes\Extensions\CertificateChainExtensions.cs:line 43
   at Certes.Cli.Commands.CertificatePemCommand.Execute(ArgumentSyntax syntax) in C:\projects\certes\src\Certes.Cli\Commands\CertificatePemCommand.cs:line 56
   at Certes.Cli.CliCore.Run(String[] args) in C:\projects\certes\src\Certes.Cli\CliCore.cs:line 35
```

Is there any other way to specify a CA other than recompiling Certes?

**Comment by fszlin** [comment]
Not from the CLI currently. I think I can add `--issuer <root-cert.pem>` option to it.

**Comment by pkiguy** [comment]
would be great indeed!

**Comment by pkiguy** [comment]
Yes, that fixes it indeed ! Thanks !

**Comment by pkiguy** [comment]
Alternatively, what about trying something like this:
[getCAFromWindowsStore.diff.txt](https://github.com/fszlin/certes/files/2192627/getCAFromWindowsStore.diff.txt)
Note: this code is completely untested....
