### ISSUE TITLE
NullReferenceException at `Certes.Acme.OrderContext.<Authorizations>d__1.MoveNext()`

### ISSUE THREAD

**Issue by ohadschn** [fszlin/certes#212]
Using https://github.com/sjkp/letsencrypt-siteextension I got the following stack trace:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Certes.Acme.OrderContext.<Authorizations>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LetsEncrypt.Azure.Core.Services.BaseHttpAuthorizationChallengeProvider.<Authorize>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LetsEncrypt.Azure.Core.Services.AcmeService.<RequestCertificate>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LetsEncrypt.Azure.Core.CertificateManager.<RequestInternalAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LetsEncrypt.Azure.Core.CertificateManager.<RequestAndInstallInternalAsync>d__15.MoveNext()
```

Looking at the code, it looks like the `Resource` in the response was null: https://github.com/fszlin/certes/blob/f9980d2d7077e3b371f6fc156077f76eaecf2dd0/src/Certes/Acme/EntityContext.cs#L50

I suggest:
1. Improve the error message to something like `Resource was empty`
1. Consider retries in such cases, which might be transient (as it was in my case)

**Comment by valeriob** [comment]
Hi,
i'm getting the same error via https://github.com/aloopkin/WinCertes :( how did you solve the problem ?

**Comment by ohadschn** [comment]
For me it was transient, I just retried and it worked..
