### ISSUE TITLE
Error exporting certificate in staging - Can not find issuer

### ISSUE THREAD

**Issue by rbjoergensen** [fszlin/certes#250]
When trying to export the certificate i get the following error when using staging.
``` c#
var certPem = cert.ToPem();
```
``` c#
Certes.AcmeException: Can not find issuer 'C=US,O=(STAGING) Internet Security Research Group,CN=(STAGING) Doctored Durian Root CA X3' for certificate 'C=US,O=(STAGING) Internet Security Research Group,CN=(STAGING) Pretend Pear X1'.
   at Certes.Pkcs.CertificateStore.GetIssuers(Byte[] der)
   at Certes.CertificateChainExtensions.ToPem(CertificateChain certificateChain, IKey certKey)
```

I found this which explains why.
https://community.certifytheweb.com/t/error-building-certificate-as-pfx-cannot-find-issuer/1253

**Comment by rbjoergensen** [comment]
Duplicate
